const mega_data = [
    {
        school_code: "VVK",
        max_period: 10,
        data_schedule: [
            {
                day: "Monday",
                schedule: [
                    { time: 1, event: "Chào cờ" },
                    { time: 2, event: "Anh Văn" },
                    { time: 3, event: "Sinh Học" },
                    { time: 4, event: "Lịch Sử" },
                    { time: 5, event: "Vật Lý" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "Vật Lý" },
                    { time: 9, event: "Toán" },
                    { time: 10, event: "Ngữ Văn" },
                ],
            },
            {
                day: "Tuesday",
                schedule: [
                    { time: 1, event: "Toán " },
                    { time: 2, event: "Toán" },
                    { time: 3, event: "TC Địa" },
                    { time: 4, event: "Tin" },
                    { time: 5, event: "Tin" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "Địa Lý" },
                    { time: 9, event: "Vật Lý" },
                    { time: 10, event: "Lịch Sử" },
                ],
            },
            {
                day: "Wednesday",
                schedule: [
                    { time: 1, event: "Hoá Học" },
                    { time: 2, event: "Vật Lý" },
                    { time: 3, event: "TC Anh Văn" },
                    { time: 4, event: "Lịch Sử" },
                    { time: 5, event: "Sinh Học" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "Thể Dục " },
                    { time: 9, event: "Ngữ Văn" },
                    { time: 10, event: "Anh Văn" },
                ],
            },
            {
                day: "thursday",
                schedule: [
                    { time: 1, event: "Địa Lý" },
                    { time: 2, event: "GDCD" },
                    { time: 3, event: "Ngữ Văn" },
                    { time: 4, event: "Toán" },
                    { time: 5, event: "TC Toán" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "Anh Văn" },
                    { time: 9, event: "Lịch Sử" },
                    { time: 10, event: "Địa Lý" },
                ],
            },
            {
                day: "friday",
                schedule: [
                    { time: 1, event: "TC Sử" },
                    { time: 2, event: "Công Nghệ" },
                    { time: 3, event: "Anh Văn" },
                    { time: 4, event: "Anh Văn" },
                    { time: 5, event: "Toán" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "GD QP-AN" },
                    { time: 9, event: "Thể Dục " },
                    { time: 10, event: "Toán" },
                ],
            },
            {
                day: "saturday",
                schedule: [
                    { time: 1, event: "Ngữ Văn" },
                    { time: 2, event: "Ngữ Văn" },
                    { time: 3, event: "Hoá Học" },
                    { time: 4, event: "SHL" },
                    { time: 5, event: "NGLL" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "" },
                    { time: 9, event: "" },
                    { time: 10, event: "" },
                ],
            },
        ],
    },
    {
        school_code: "SGU",
        max_period: 11,
        data_schedule: [
            {
                day: "Monday",
                schedule: [
                    { time: 1, event: "" },
                    { time: 2, event: "" },
                    { time: 3, event: "" },
                    { time: 4, event: "" },
                    { time: 5, event: "" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "" },
                    { time: 9, event: "" },
                    { time: 10, event: "" },
                    { time: 10, event: "" },
                ],
            },
            {
                day: "Tuesday",
                schedule: [
                    { time: 1, event: "QLDA" },
                    { time: 2, event: "QLDA" },
                    { time: 3, event: "QLDA" },
                    { time: 4, event: "QLDA" },
                    { time: 5, event: "QLDA" },
                    { time: 6, event: "C#" },
                    { time: 7, event: "C#" },
                    { time: 8, event: "C#" },
                    { time: 9, event: "C#" },
                    { time: 10, event: "C#" },
                    { time: 10, event: "" },
                ],
            },
            {
                day: "Wednesday",
                schedule: [
                    { time: 1, event: "Tiếng Anh I" },
                    { time: 2, event: "Tiếng Anh I" },
                    { time: 3, event: "Bóng Bàn" },
                    { time: 4, event: "Bóng Bàn" },
                    { time: 5, event: "" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "" },
                    { time: 9, event: "" },
                    { time: 10, event: "" },
                    { time: 10, event: "" },
                ],
            },
            {
                day: "thursday",
                schedule: [
                    { time: 1, event: "" },
                    { time: 2, event: "" },
                    { time: 3, event: "" },
                    { time: 4, event: "" },
                    { time: 5, event: "" },
                    { time: 6, event: "" },
                    { time: 7, event: "" },
                    { time: 8, event: "" },
                    { time: 9, event: "" },
                    { time: 10, event: "" },
                    { time: 10, event: "" },
                ],
            },
            {
                day: "friday",
                schedule: [
                    { time: 1, event: "LS Đảng" },
                    { time: 2, event: "LS Đảng" },
                    { time: 3, event: "" },
                    { time: 4, event: "ATBMHTTT" },
                    { time: 5, event: "ATBMHTTT" },
                    { time: 6, event: "ATBMHTTT" },
                    { time: 7, event: "ATBMHTTT" },
                    { time: 8, event: "" },
                    { time: 9, event: "Seminar" },
                    { time: 10, event: "Seminar" },
                    { time: 11, event: "Seminar" },
                ],
            },
            {
                day: "saturday",
                schedule: [
                    { time: 1, event: "" },
                    { time: 2, event: "" },
                    { time: 3, event: "" },
                    { time: 4, event: "" },
                    { time: 5, event: "" },
                    { time: 6, event: "J2EE" },
                    { time: 7, event: "J2EE" },
                    { time: 8, event: "J2EE" },
                    { time: 9, event: "J2EE" },
                    { time: 10, event: "J2EE" },
                    { time: 10, event: "" },
                ],
            },
        ],
    },
];